import { getDataBooking } from "@/app/api/params/param";
import "./globals.css";
import { AddTicketButton } from "@/services/add-ticket-button";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout() {
  let x = await getDataBooking();
  return (
    <html lang='en'>
      <body>
        asd {x?.total ? x?.total : "sadads"}
        {x.products.map((item: any) => {
          return <div>{item.title}</div>;
        })}
        <div>saasddsad</div>
        <AddTicketButton />
      </body>
    </html>
  );
}
